import type { IReportCard } from '../components/portal/Reports/@types/reportCard.d';

// Reshaped to mirror the real `IReportCard` endpoint response (Task 13) — this
// is what powers the offline `/preview` route via ResultCardPreview. Test 8
// deliberately omits Al Quran and Islamiat from `marks` (not a substituted 0)
// to exercise the same blank-cell path as the school's real card.
export const ResultSampleData: IReportCard = {
  institute: {
    name: 'FARRUKH ACADEMY OF SCIENCE',
    address: 'Dhobi Ghat Stop Near Nafeerabad Graveyard Shalimar Town Lahore',
    phone: '+92 324 0012215',
  },
  student: {
    name: 'Qasim',
    fatherName: 'Amjad',
    class: '9th',
    rollNumber: '615872',
  },
  title: 'MONTHLY ASSESSMENT REPORT',
  subjects: [
    { externalId: 'maths', name: 'Maths' },
    { externalId: 'urdu', name: 'Urdu' },
    { externalId: 'english', name: 'English' },
    { externalId: 'al-quran', name: 'Al Quran' },
    { externalId: 'islamiat', name: 'Islamiat' },
    { externalId: 'bio-com', name: 'Bio/Computer' },
    { externalId: 'physics', name: 'Physics' },
    { externalId: 'chemistry', name: 'Chemistry' },
  ],
  rows: [
    {
      testName: 'Test 1',
      marks: {
        maths: { obtained: 30, max: 30 },
        urdu: { obtained: 48, max: 50 },
        english: { obtained: 54, max: 60 },
        'al-quran': { obtained: 30, max: 30 },
        islamiat: { obtained: 28, max: 30 },
        'bio-com': { obtained: 29, max: 30 },
        physics: { obtained: 28, max: 30 },
        chemistry: { obtained: 28, max: 30 },
      },
      total: 275,
      maxTotal: 290,
      percentage: 94.83,
      grade: 'A+',
    },
    {
      testName: 'Test 2',
      marks: {
        maths: { obtained: 22, max: 30 },
        urdu: { obtained: 47, max: 50 },
        english: { obtained: 58, max: 60 },
        'al-quran': { obtained: 30, max: 30 },
        islamiat: { obtained: 27, max: 30 },
        'bio-com': { obtained: 27, max: 30 },
        physics: { obtained: 27, max: 30 },
        chemistry: { obtained: 25, max: 30 },
      },
      total: 263,
      maxTotal: 290,
      percentage: 90.69,
      grade: 'A+',
    },
    {
      testName: 'Test 3',
      marks: {
        maths: { obtained: 23, max: 30 },
        urdu: { obtained: 42, max: 50 },
        english: { obtained: 54, max: 60 },
        'al-quran': { obtained: 30, max: 30 },
        islamiat: { obtained: 29, max: 30 },
        'bio-com': { obtained: 29, max: 30 },
        physics: { obtained: 26, max: 30 },
        chemistry: { obtained: 26, max: 30 },
      },
      total: 259,
      maxTotal: 290,
      percentage: 89.31,
      grade: 'A+',
    },
    {
      testName: 'Test 4',
      marks: {
        maths: { obtained: 29, max: 30 },
        urdu: { obtained: 47, max: 50 },
        english: { obtained: 58, max: 60 },
        'al-quran': { obtained: 30, max: 30 },
        islamiat: { obtained: 24, max: 30 },
        'bio-com': { obtained: 27, max: 30 },
        physics: { obtained: 28, max: 30 },
        chemistry: { obtained: 30, max: 30 },
      },
      total: 273,
      maxTotal: 290,
      percentage: 94.14,
      grade: 'A+',
    },
    {
      testName: 'Test 5',
      marks: {
        maths: { obtained: 28, max: 30 },
        urdu: { obtained: 41, max: 50 },
        english: { obtained: 57, max: 60 },
        'al-quran': { obtained: 30, max: 30 },
        islamiat: { obtained: 29, max: 30 },
        'bio-com': { obtained: 24, max: 30 },
        physics: { obtained: 27, max: 30 },
        chemistry: { obtained: 28, max: 30 },
      },
      total: 264,
      maxTotal: 290,
      percentage: 91.03,
      grade: 'A+',
    },
    {
      testName: 'Test 6',
      marks: {
        maths: { obtained: 26, max: 30 },
        urdu: { obtained: 36, max: 50 },
        english: { obtained: 56, max: 60 },
        'al-quran': { obtained: 29, max: 30 },
        islamiat: { obtained: 26, max: 30 },
        'bio-com': { obtained: 26, max: 30 },
        physics: { obtained: 26, max: 30 },
        chemistry: { obtained: 28, max: 30 },
      },
      total: 253,
      maxTotal: 290,
      percentage: 87.24,
      grade: 'A+',
    },
    {
      testName: 'Test 7',
      marks: {
        maths: { obtained: 27, max: 30 },
        urdu: { obtained: 44, max: 50 },
        english: { obtained: 54, max: 60 },
        'al-quran': { obtained: 29, max: 30 },
        islamiat: { obtained: 26, max: 30 },
        'bio-com': { obtained: 28, max: 30 },
        physics: { obtained: 28, max: 30 },
        chemistry: { obtained: 30, max: 30 },
      },
      total: 266,
      maxTotal: 290,
      percentage: 91.72,
      grade: 'A+',
    },
    {
      testName: 'Test 8',
      // Al Quran and Islamiat were not examined in this test — their keys are
      // omitted entirely (not zeroed) so the card renders blank cells.
      marks: {
        maths: { obtained: 26, max: 30 },
        urdu: { obtained: 40, max: 50 },
        english: { obtained: 58, max: 60 },
        'bio-com': { obtained: 22, max: 30 },
        physics: { obtained: 29, max: 30 },
        chemistry: { obtained: 26, max: 30 },
      },
      total: 201,
      maxTotal: 230,
      percentage: 87.39,
      grade: 'A+',
    },
  ],
  subjectTotals: {
    maths: { obtained: 211, max: 240 },
    urdu: { obtained: 345, max: 400 },
    english: { obtained: 449, max: 480 },
    'al-quran': { obtained: 208, max: 210 },
    islamiat: { obtained: 189, max: 210 },
    'bio-com': { obtained: 212, max: 240 },
    physics: { obtained: 219, max: 240 },
    chemistry: { obtained: 221, max: 240 },
  },
  overall: {
    obtainedMarks: 2054,
    totalMarks: 2260,
    percentage: 90.88,
    grade: 'A+',
    status: 'PASS',
    remarks:
      "Excellent Performance Overall. Don't Be Lazy. More Hardwork Makes You More Successful. In sha ALLAH",
  },
  conduct: {
    behaviour: 'Excellent',
    uniformCleanliness: 'Excellent',
  },
  position: { rank: 2, outOf: 35 },
};

// test Data constants
export const MonthList = [
  { value: 1, label: 'January' },
  { value: 2, label: 'February' },
  { value: 3, label: 'March' },
  { value: 4, label: 'April' },
  { value: 5, label: 'May' },
  { value: 6, label: 'June' },
  { value: 7, label: 'July' },
  { value: 8, label: 'August' },
  { value: 9, label: 'September' },
  { value: 10, label: 'October' },
  { value: 11, label: 'November' },
  { value: 12, label: 'December' },
];
